<?php
/* Author: Plamen Vasileff */

$labels = array();
$labels['buttonjunk'] = 'Маркирай като спам';
$labels['asjunk'] = 'Като спам';
$labels['buttonnotjunk'] = 'Маркирай като желано';
$labels['asnotjunk'] = 'Не е спам';
$labels['notjunk'] = 'Не е спам';

$messages = array();
$messages['reportedasjunk'] = 'Успешно отбелязахте съобщението като спам';
$messages['reportedasnotjunk'] = 'Успешно отбелязахте съобщението като желано';
