<?php
/* Author: Christian Bregnedal */
/* www.bregnedalsystems.dk     */

$labels = array();
$labels['buttonjunk'] = 'Marker som spam';
$labels['markasjunk'] = 'Som spam';
$labels['buttonnotjunk'] = 'Denne meddelelse er ikke spam';
$labels['markasnotjunk'] = 'Som ikke spam';
$labels['notjunk'] = 'Ikke spam';

$messages = array();
$messages['reportedasjunk'] = 'Succesfuld rapporteret som spam';
$messages['reportedasnotjunk'] = 'Succesfuld rapporteret som ikke spam';
