<?php
/* Author: Rrainer Rhalbmann */

$labels = array();
$labels['buttonjunk'] = 'Als SPAM markieren';
$labels['markasjunk'] = 'Als SPAM';
$labels['buttonnotjunk'] = 'Diese Nachricht ist kein SPAM';
$labels['markasnotjunk'] = 'Kein SPAM';

$messages = array();
$messages['reportedasjunk'] = 'Erfolgreich als SPAM gemeldet';
$messages['reportedasnotjunk'] = 'Nachricht in den Posteingang verschoben';

?>