<?php
/* Author: Philip Weir */

$labels = array();
$labels['buttonjunk'] = 'This message is spam';
$labels['asjunk'] = 'As spam';
$labels['markasjunk'] = 'Mark as spam';
$labels['buttonnotjunk'] = 'This message is not spam';
$labels['asnotjunk'] = 'As not spam';
$labels['markasnotjunk'] = 'Mark as not spam';
$labels['notjunk'] = 'Not spam';

$messages = array();
$messages['reportedasjunk'] = 'Successfully reported as spam';
$messages['reportedasnotjunk'] = 'Successfully reported as not spam';
