<?php
/* Author: Attila Sipos */

$labels = array();
$labels['buttonjunk'] = 'Megjelölés levélszemétként';
$labels['asjunk'] = 'Levélszemétként';
$labels['buttonnotjunk'] = 'Ez az üzenet nem levélszemét';
$labels['asnotjunk'] = 'Nem levélszemét';
$labels['notjunk'] = 'Nem levélszemét';

$messages = array();
$messages['reportedasjunk'] = 'Sikeresen jelentve, mint levélszemét';
$messages['reportedasnotjunk'] = 'Az üzenet visszakerült az Érkezett levelek mappába';
