<?php
/* Author: Mārtiņš Dzērve */

$labels = array();
$labels['buttonjunk'] = 'Atzīmēt mēstules';
$labels['asjunk'] = 'Kā mēstuli';
$labels['buttonnotjunk'] = 'Atzīmēt ne-mēstules';
$labels['asnotjunk'] = 'Kā ne-mēstule';
$labels['notjunk'] = 'Ne-mēstules';

$messages = array();
$messages['reportedasjunk'] = 'Veiksmīgi ziņots par mēstuli';
$messages['reportedasnotjunk'] = 'Veiksmīgi ziņots par ne-mēstuli';
