<?php
/* Author: Marcin Zawadzki */

$labels = array();
$labels['buttonjunk'] = 'Oznacz jako Spam';
$labels['markasjunk'] = 'Jako Spam';
$labels['buttonnotjunk'] = 'Ta wiadomoœæ nie jest Spamem';
$labels['markasnotjunk'] = 'Nie Spam';

$messages = array();
$messages['reportedasjunk'] = 'Pomyœlnie oznaczono jako Spam';
$messages['reportedasnotjunk'] = 'Wiadomoœæ przeniesiona do odebranych';

?>